apiVersion: v2
name: palladium
description: none

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: mongodb
    version: "13.1.7"
    repository: "https://charts.bitnami.com/bitnami"
