apps:
  server:
    enabled: true
    service:
      type: ClusterIP
      port: "8080"
    deployment:
      revisions: 0
      strategy:
        type: Recreate
      image:
        ref: "harbor.chinook.k8s.voidpointergroup.com/palladium/palladium-server:nightly"
        pull_policy: Always
    secrets:
      config:
        config: |-
          version: 0.1.0
          server:
            address: "0.0.0.0:8080"
          mondogb:
            endpoint: "mongodb://palladium-mongodb:27017"

mongodb:
  auth:
    enabled: false
