{{- if .Values.apps.server.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-palladium-server-config
type: Opaque
stringData:
  {{- toYaml .Values.apps.server.secrets.config | nindent 2 }}
{{ end }}
